### ISSUE TITLE
Certain answers may lead to AC without indent check

### ISSUE THREAD

**Issue by kishore-ganesh** [kalpaj12/Codeforces-QuickBuild#1]
"de and "d
re"        "ere"

are considered to be the same.

**Comment by kalpaj12** [comment]
There is a hack'ish way to work around this issue. It is by comparing the number of characters in each line. WA is already handled. This is just a sub division to cross check WA, when file have the same output but indent is not the same

**Comment by kalpaj12** [comment]
I guess this should work without affecting performance.

**Comment by kishore-ganesh** [comment]
Yes but that wouldn't work for outputs like "de c" when the answer is "dec"

**Comment by kalpaj12** [comment]
yup, and that's why I need help with this.

**Comment by kalpaj12** [comment]
![screenshot from 2019-03-02 08-24-34](https://user-images.githubusercontent.com/41864755/53676173-ce112f00-3cc4-11e9-8d72-05c8ee5406e8.png)
